
MACRO(MACI_TPL_REPORT TPLNAME)

	IF("${TPL_ENABLE_${TPLNAME}}" STREQUAL "ON")
		MESSAGE(STATUS "TPL_ENABLE_${TPLNAME}:BOOL = ON")
	ELSE()
		MESSAGE(STATUS "TPL_ENABLE_${TPLNAME}:BOOL = OFF")
		RETURN()
	ENDIF()

ENDMACRO()

