#
# Maci_TPL_TAU.cmake: TAU Third-Party Package
#

INCLUDE(MACI_TPL_CHECK_INPUT)
INCLUDE(MACI_TPL_REPORT)

OPTION(TPL_ENABLE_TAU "Enable TAU" OFF)

MACI_TPL_REPORT(TAU)
IF(NOT TPL_ENABLE_TAU)
	RETURN()
ENDIF()

# The following variables must be set on the command
# line:
#
# - TAU_INCLUDE_DIRS:PATH
# - TAU_LIBRARY_DIRS:PATH
# - TUA_LIBRARY_NAMES:STRING
#
MACI_TPL_CHECK_INPUT(TAU)

INCLUDE_DIRECTORIES(${TAU_INCLUDE_DIRS})
LINK_DIRECTORIES   (${TAU_LIBRARY_DIRS})

LIST(APPEND LIBS2 ${TAU_LIBRARY_NAMES})
LIST(APPEND LIBS3 ${TAU_LIBRARY_NAMES})

ADD_DEFINITIONS(-DPROFILING_ON -DTAU_STDCXXLIB)

SET(HAVE_TAU 1)

