#
# Maci_TPL_PETSc.cmake: PETSc Third-Party Package
#

INCLUDE(MACI_TPL_CHECK_INPUT)
INCLUDE(MACI_TPL_REPORT)

OPTION(TPL_ENABLE_PETSc "Enable PETSc" OFF)

MACI_TPL_REPORT(PETSc)
IF(NOT TPL_ENABLE_PETSc)
	RETURN()
ENDIF()

# The following variables must be set on the command
# line:
#
# - PETSc_INCLUDE_DIRS:PATH
# - PETSc_LIBRARY_DIRS:PATH
# - PETSc_LIBRARY_NAMES:STRING
#
MACI_TPL_CHECK_INPUT(PETSc)

INCLUDE_DIRECTORIES(${PETSc_INCLUDE_DIRS})
LINK_DIRECTORIES   (${PETSc_LIBRARY_DIRS})

LIST(APPEND SRC2 linalg/PetscSolver.cc)
LIST(APPEND SRC3 linalg/PetscSolver.cc)

LIST(APPEND LIBS2 ${PETSc_LIBRARY_NAMES})
LIST(APPEND LIBS3 ${PETSc_LIBRARY_NAMES})

SET(HAVE_PETSC 1)

