#
# Maci_TPL_GA.cmake: Global Array Third-Party Package
#

INCLUDE(MACI_TPL_CHECK_INPUT)
INCLUDE(MACI_TPL_REPORT)

OPTION(TPL_ENABLE_GA "Enable Global Array" OFF)

MACI_TPL_REPORT(GA)
IF(NOT TPL_ENABLE_GA)
    RETURN()
ENDIF()

# The following variables must be set on the command
# line:
#
# - GA_INCLUDE_DIRS:PATH
# - GA_LIBRARY_DIRS:PATH
# - GA_LIBRARY_NAMES:STRING
#
MACI_TPL_CHECK_INPUT(GA)

INCLUDE_DIRECTORIES(${GA_INCLUDE_DIRS})
LINK_DIRECTORIES   (${GA_LIBRARY_DIRS})

LIST(APPEND SRC2 GlobalArray.cc)
LIST(APPEND SRC3 GlobalArray.cc)

LIST(APPEND LIBS2 ${GA_LIBRARY_NAMES})
LIST(APPEND LIBS3 ${GA_LIBRARY_NAMES})

SET(HAVE_GA 1)

