
IF(NOT CMAKE_BUILD_TYPE)
        set(CMAKE_BUILD_TYPE Debug)
ENDIF()

IF(CMAKE_BUILD_TYPE STREQUAL Debug)
	# Intel: -diag-disable 981,1418,444,383,869,1572,1419,280
#	IF(CMAKE_COMPILER_IS_GNUCC)
        	ADD_DEFINITIONS(-DDEBUG -Wall -O0 -ggdb -D"'ASSERT(X)=assert(X)'")
#	ENDIF()
ENDIF()

IF(CMAKE_BUILD_TYPE STREQUAL Release)
#	IF(CMAKE_COMPILER_IS_GNUCC)
	   	ADD_DEFINITIONS(-DNDEBUG -Wall -O3 -D"'ASSERT(X)=(void )(X)'")
#	ENDIF()
ENDIF()

